### ISSUE TITLE
Datavault undefined local variable

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#61] opened 2015-03-12 18:19 UTC
When trying to `cd` to an as-yet non-existing directory:

```python
exceptions.UnboundLocalError: local variable 'create' referenced before assignment
```

**Comment by ejeffrey** [comment] 2015-03-12 18:32
This is fixed in git, but hasn't been pushed to skynet.  Since it is just
the wrong error message it doesn't seem like a high priority.

**Comment by ejeffrey** [comment] 2015-05-13 00:57
Duplicate of #7

**Closed by ejeffrey** 2015-05-13 00:57 UTC
Labels: bug
