### ISSUE TITLE
Intermittent errors during datataking

### ISSUE THREAD

**Issue by rb25** [martinisgroup/servers#180] opened 2015-06-06 05:48 UTC
Getting errors where dataking routines stop intermittently for no apparent reason. Each time the scala direct ethernet is stopped. Starting that (and then the fpga and qubit server) fixes it for ~20-30 mins, then it happens again.

stack trace is below.

```PYTHON
In [10]: sq.orbitNMsettling(s,'q3',param_names = param_names, zdelt=zdelt,m=20,k
=40,maxfun=100)
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-10-0b9f72de7678> in <module>()
----> 1 sq.orbitNMsettling(s,'q3',param_names = param_names, zdelt=zdelt,m=20,k=
40,maxfun=100)

U:\Rami\pyle\pyle\dataking\singleQubit.pyc in orbitNMsettling(Sample, measure, p
aram_names, zdelt, name, m, k, stats, maxfun, interleaved, collect, save, noisy)

   4637     sweep = optim.map_optimizers(func, optimizers, averages=k,
   4638                                  noisy=noisy)
-> 4639     data = sweeps.run(optim.pass_thru, sweep, dataset=dataset, save=save
, noisy=noisy, pipesize=1)
   4640     if collect:
   4641         return data

U:\Rami\pyle\pyle\dataking\sweeps.pyc in run(func, sweep, save, dataset, abortab
le, abortPrefix, collect, noisy, pipesize)
    192         collect=collect,
    193         noisy=noisy,
--> 194         pipesize=pipesize
    195     )
    196

U:\Rami\pyle\pyle\dataking\sweeps.pyc in _run(func, sweep, save, dataset, aborta
ble, abortPrefix, collect, noisy, pipesize)
    229         params = dataset.params
    230         name = dataset.name
--> 231         data = np.vstack(it)
    232         return pyle.datavault.LocalDataSet(data, independents, dependent
s,
    233             params, name)

C:\Python27\lib\site-packages\numpy\core\shape_base.pyc in vstack(tup)
    226
    227     """
--> 228     return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    229
    230 def hstack(tup):

U:\Rami\pyle\pyle\datasaver.pyc in capture(self, iterable)
    141         #     time.sleep(random.expovariate(0.01))
    142         with self as dataset:
--> 143             for data in iterable:
    144                 dataset.add(data)
    145                 yield data

U:\Rami\pyle\pyle\pipeline.pyc in <genexpr>(***failed resolving arguments***)
     70     # for each value coming out of the iterable
     71     if size <= 1:
---> 72         return (call(function, x) for x in iterable)
     73
     74     # Otherwise, create a generator to run multiple pipeline stages

U:\Rami\pyle\pyle\dataking\sweeps.pyc in checkAbort(iterable, labels, prefix)
    353     idx = -1
    354     last = None
--> 355     for val in iterable:
    356         curr = val
    357         for i in prefix:

U:\Rami\pyle\pyle\dataking\optimization\optimization.pyc in map_optimizers(func,
 optimizers, averages, noisy, max_evaluations)
    232
    233         # run the pipeline to completion and collect results
--> 234         data = np.array(list(pipe))
    235
    236         avg_errors = np.mean(data, axis=0)

U:\Rami\pyle\pyle\pipeline.pyc in gen()
     99             runners.append(runner)
    100             if len(runners) >= size:
--> 101                 done, result = advance()
    102                 if done:
    103                     yield result

U:\Rami\pyle\pyle\pipeline.pyc in advance()
     80             # loop over runners, advancing until one completes
     81             for runner in itertools.cycle(runners):
---> 82                 runner.advance()
     83                 if runner.done:
     84                     break

U:\Rami\pyle\pyle\pipeline.pyc in advance(self)
    123         if not self.done:
    124             try:
--> 125                 self.gen.next()
    126             except _DefGen_Return, e:
    127                 self.done = True

U:\Rami\pyle\pyle\pipeline.pyc in _run(gen)
    170                     result = result.wait()
    171                 except Exception, e:
--> 172                     result = gen.throw(e)
    173             elif is_generator(result):
    174                 try:

U:\Rami\pyle\pyle\dataking\singleQubit.pyc in func(args)
   4629         alg.compile()
   4630
-> 4631         data = yield Sample.run(alg, stats, dataFormat='iqRaw')
   4632         prob = readout.IQToProbs(data, alg.qubits, measure)
   4633         returnValue([1-np.squeeze(prob)[0]])

Error: (0) java.util.concurrent.ExecutionException: org.labrad.errors.LabradExce
ption: [GHz FPGAs] Remote Traceback (most recent call last):
  File "C:\pylabrad\labrad\server.py", line 262, in handleRequest
    result = yield setting.handleRequest(self, c.data, data)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1097, in
_inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in t
hrowExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "ghz_fpga_server.py", line 1476, in run_sequence
    timingOrder)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1097, in
_inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in t
hrowExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "ghz_fpga_server.py", line 636, in run
    yield loadDone # wait until load is finished.
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1099, in
_inlineCallbacks
    result = g.send(result)
  File "ghz_fpga_server.py", line 820, in sendAll
    raise Exception(msg)
exceptions.Exception: Error(s) occured during Load:
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]


        at org.labrad.RequestReceiver.get(RequestReceiver.java:111)
        at org.labrad.RequestReceiver.get(RequestReceiver.java:41)
        at org.labrad.ServerConnection.sendAndWait(ServerConnection.java:526)
        at org.labrad.qubits.QubitContext.run_experiment(QubitContext.java:1106)

        at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.labrad.handlers.SingleArgVoidHandler.handle(SingleArgVoidHandler.
java:24)
        at org.labrad.ContextManager.processRequest(ContextManager.java:143)
        at org.labrad.ContextManager.access$100(ContextManager.java:15)
        at org.labrad.ContextManager$RequestProcessor.run(ContextManager.java:18
1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.labrad.errors.LabradException: [GHz FPGAs] Remote Traceback (most
 recent call last):
  File "C:\pylabrad\labrad\server.py", line 262, in handleRequest
    result = yield setting.handleRequest(self, c.data, data)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1097, in
_inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in t
hrowExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "ghz_fpga_server.py", line 1476, in run_sequence
    timingOrder)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1097, in
_inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in t
hrowExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "ghz_fpga_server.py", line 636, in run
    yield loadDone # wait until load is finished.
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1099, in
_inlineCallbacks
    result = g.send(result)
  File "ghz_fpga_server.py", line 820, in sendAll
    raise Exception(msg)
exceptions.Exception: Error(s) occured during Load:
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]
Traceback (failure with no frames): <class 'labrad.types.Error'>: (1) java.lang.
Exception: no such server: 7 [payload=None]


        at org.labrad.RequestReceiver.set(RequestReceiver.java:171)
        at org.labrad.RequestDispatcher.finishRequest(RequestDispatcher.java:89)

        at org.labrad.ServerConnection.handlePacket(ServerConnection.java:587)
        at org.labrad.ServerConnection.access$100(ServerConnection.java:77)
        at org.labrad.ServerConnection$1.run(ServerConnection.java:314)
        ... 1 more
 [payload=None]

In [11]:
```

**Comment by maffoo** [comment] 2015-06-08 18:43
Dupe of #182. See discussion on that issue.

**Closed by maffoo** 2015-06-08 18:43 UTC
