### ISSUE TITLE
Scala Direct Ethernet drops out every 10-20 mins

### ISSUE THREAD

**Issue by rb25** [martinisgroup/servers#190] opened 2015-06-16 16:45 UTC
@maffoo @pomalley @JulianSKelly 
I'm seeing crashes of Scala Direct Ethernet. It's version 1.0.0-M1. The alternative is to run the old direct ethernet, but that's slow. How can I help?

**Comment by maffoo** [comment] 2015-06-16 16:54
@rb25 I didn't realize the frequency was so high; in the past I had heard it was like once or twice a day. Either way we need to fix it, of course. I'd like to powwow on this; do you mind if I hop on redheatdos?

**Comment by rb25** [comment] 2015-06-16 17:15
Yes, please go ahead

**Comment by maffoo** [comment] 2015-06-18 20:35
Closing as dupe of #182.

**Closed by maffoo** 2015-06-18 20:35 UTC
